#Jonathan Borowsky
#Grabe lab
#3/11/26

import os
import pymol
from pymol import cmd

upperpath = "/home/jonathan/Documents/grabelab/cftr/independent-partial-dissociation/"
folders = [ ['nonlip_glpg_1',   '001913-000187-ancestors-2.5A-20A'],
            ['nonlip_glpg_2',   '000691-000198-ancestors-2.5A-20A'],
            ['lip_glpg_1',      '001998-000130-ancestors-2.5A-20A'],
            ['lip_glpg_2',      '001986-000211-ancestors-2.5A-20A']]

bins = [1,10,20,30,40]
n_frames_per_we_timestep = 3

#generated by /home/jonathan/Documents/grabelab/cftr/cftr-potentiator-SAR/water-membrane-permeation/plot_pcs_get_median_frames.ipynb
#each row is a trajectory corresponding to one of the above files, each column is a different bin
we_rounds_all =   [ [ 473,  1286,   1678,   1788,  1856],
                    [  82,   269,    583,    647,   672],
                    [ 539,  1569,   1819,   1937,  1985],
                    [  78,  1379,   1756,   1909,  1957 ]]


def set_graphics():
    cmd.do("bg white")
    cmd.do("set ray_shadow=off")
    cmd.do("set cartoon_fancy_helices, 1")
    cmd.do("set specular, off")
    cmd.do("set orthoscopic, 1")
    cmd.do("set depth_cue, 1") #<--enable fog
    cmd.do("set auto_zoom, off")
    cmd.do("set sphere_quality, 5")
    cmd.do("set opaque_background, off")
    cmd.do("set ray_opaque_background, off")
    cmd.do("set antialias, 2")
    cmd.do("set ray_trace_mode, 1")
    cmd.do("set ray_trace_color, black")
    cmd.set("ray_trace_gain", 0.05)

set_graphics()


for folder, we_rounds in zip(folders, we_rounds_all):
    fnames = []
    for i, we_round in enumerate(we_rounds):

        #------------------------------------load data--------------------------------------------
        cmd.delete("all")

        cmd.load(f"{upperpath}/nonlip_glpg_1/topology/input.gro", "viewref")

        objname = "cftrframe"

        cmd.load(f"{upperpath}/{folder[0]}/topology/input.gro", objname)

        trj_files = [f for f in os.listdir(f"{upperpath}/{folder[0]}/2.5A-20A/{folder[1]}/") if (f.endswith("-traj_comp.xtc") and int(f[0:6]) == we_round+1)]
        cmd.load_traj(f"{upperpath}/{folder[0]}/2.5A-20A/{folder[1]}/{trj_files[0]}", objname, start=2, stop=2)

        cmd.align(objname, "object viewref and (resi 77-149 or resi 192-245 or resi 298-362 or resi 988-1034 or resi 857-889 or resi 900-942 or resi 1094-1154)")
        
        #secondary structure assignment
        cmd.dss(objname)

        #hide/show and rescale
        cmd.hide("everything")

        cmd.show("cart", f"{objname} and poly")

        siteresis = "304+305+308+309+312+313+316+865+869+872+873+876+877+926+927+928+930+931+932+933" #229+233+236+

        cmd.show("sticks",           f"{objname} and resi {siteresis} and not elem H") #and not name C+N+O 
        #cmd.show("spheres",          f"{objname} and resi {siteresis} and name CA")
        #cmd.set("sphere_scale", 0.3, f"{objname} and resi {siteresis} and name CA")

        cmd.show("sticks", f"{objname} and resn LJP and not elem H")
        util.cbac("resn LJP")

        cmd.show("spheres", f"byres(({objname} and resn TP3) within 5 of ({objname} and poly))")

        util.cbaw("poly")
        util.cbag("resi " + siteresis)

        #matches heatmap panels
        cmd.set_view((\
        0.933495879,    0.014861241,   -0.358267784,\
        -0.357729882,    0.107290752,   -0.927639842,\
        0.024650594,    0.994103849,    0.105471313,\
        -0.000507705,   -0.003106263, -105.927444458,\
        39.996837616,   38.508853912,  114.650337219,\
        85.477149963,  126.379646301,   20.000000000 ))

        #zoomed but does not match
        # set_view (\
        #      0.933495879,    0.014861241,   -0.358267784,\
        #     -0.357729882,    0.107290752,   -0.927639842,\
        #      0.024650594,    0.994103849,    0.105471313,\
        #     -0.000507705,   -0.003106263,  -89.297584534,\
        #     39.996837616,   38.508853912,  114.650337219,\
        #     68.847259521,  109.749748230,   20.000000000 )

        fname = f"/home/jonathan/Documents/grabelab/cftr/cftr-potentiator-SAR/water-membrane-permeation/figures/{folder[0]}-{folder[1]}-round-{we_round}-bin{bins[i]}"
        cmd.png(fname, width=1200, height=1000, dpi=600, ray=1)
        fnames.append(fname)

        #break
    print(fnames)
    #break
